# -*- coding: utf-8 -*-
"""Copy of Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-CUac-QrJXjvFkfvQpCY0s-sOP0w2yt
"""

import math
a=int(input("Enter first side: "))
b=int(input("Enter second side: "))
c=int(input("Enter third side: "))
s=(a+b+c)/2
area=math.sqrt(s*(s-a)*(s-b)*(s-c))
print("Area of the triangle is:",round(area,2))
 
 celsius = 37.5
 
 
fahrenheit = (celsius * 1.8) + 32
print('%0.1f degree Celsius is equal to %0.1f degree Fahrenheit'%(celsius,fahrenheit))
 
 
def areaRectangle(a, b): 
 
    return (a * b) 
 
 
a = 8; 
 
b = 6; 
 
print ("Area = ", areaRectangle(a, b))
 
 
def perimeterRectangle(a, b): 
 
    return (2*(a + b)) 
 
  
 
 
a = 7; 
 
b = 4; 
 
 
 
print ("Perimeter = ",perimeterRectangle(a, b))
 
 
PI = 3.1415
 
 
 
def circumference(r): 
 
    return (2 * PI * r) 
 
 
print ('%.3f' % circumference(3))
 
 
x = 45
 
y = 80
 
 
 
temp = x 
 
x = y 
 
y = temp 
 
  
 
print("Value of x",x) 
 
print("Value of y:",y)