# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Np9kYsubH90uAdJ4f_re2jsE0J-6HTW
"""

first='100'
second='150' 
print(first+second)

b=6
b+b

b=10
b

b=b+b
b



first='120'
second='100' 
print(first+second)

a=1.2
b=3.1
sum=float(a)+float(b)
print("The sum of is",sum)