# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Anil6600/f85efbb8b20f2fa2a1382d3d8c069c44/untitled5.ipynb
"""

def simple_interest (p, t, r) 
print('principal', p) 
print('time period', t) 
print('interest', r) 
SI= (p*t*r) /100
print('simple_interest', SI) 
return SI
simple_interest(8,6,8)

def simple_interest(p,t,r): 
 
    print('The principal is', p) 
 
    print('The time period is', t) 
 
    print('The rate of interest is',r) 
 
      
 
    SI = (p * t * r)/100
 
      
 
    print('The Simple Interest is', SI) 
 
    return SI
 
      
 
 
simple_interest(8, 6, 8)